/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otrosComponentes;

import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Alumno
 */
public class FrmEjemploCombo extends javax.swing.JFrame {

    /**
     * Creates new form FrmEjemploCombo
     */
    public FrmEjemploCombo() {
        initComponents();
        
        cargarAutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboAutos = new javax.swing.JComboBox<>();
        btnObtenerSeleccionado = new javax.swing.JButton();
        lblObtener = new javax.swing.JLabel();
        spnIndice = new javax.swing.JSpinner();
        lblSeleccionado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JFormattedTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cboAutos.setModel(new javax.swing.DefaultComboBoxModel<>());
        cboAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboAutosActionPerformed(evt);
            }
        });

        btnObtenerSeleccionado.setText("Obtener");
        btnObtenerSeleccionado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerSeleccionadoActionPerformed(evt);
            }
        });

        lblObtener.setText("Seleccionado");

        spnIndice.setModel(new javax.swing.SpinnerNumberModel(0, 0, 9, 1));
        spnIndice.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnIndiceStateChanged(evt);
            }
        });

        lblSeleccionado.setText("Obtener");

        jLabel1.setText("Marca");

        jLabel2.setText("Modelo");

        try {
            txtModelo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnAgregar.setMnemonic('a');
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setMnemonic('e');
        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSeleccionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnObtenerSeleccionado)
                        .addGap(37, 37, 37)
                        .addComponent(lblObtener, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(202, 202, 202))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(spnIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136)
                                .addComponent(btnAgregar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSeleccionado)
                            .addComponent(btnEliminar))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnObtenerSeleccionado)
                            .addComponent(lblObtener, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(spnIndice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAgregar)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboAutosActionPerformed
     lblSeleccionado.setText(cboAutos.getSelectedItem().toString());
     
     spnIndice.setValue(cboAutos.getSelectedIndex());
    }//GEN-LAST:event_cboAutosActionPerformed

    private void btnObtenerSeleccionadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerSeleccionadoActionPerformed
        Auto seleccion =(Auto)cboAutos.getSelectedItem();
        
        lblObtener.setText(seleccion.getMarca());
    }//GEN-LAST:event_btnObtenerSeleccionadoActionPerformed

    private void spnIndiceStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnIndiceStateChanged
        cboAutos.setSelectedIndex((int)spnIndice.getValue());  
    }//GEN-LAST:event_spnIndiceStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String marca = txtMarca.getText().trim();
        
        if(marca.isEmpty()){
            System.out.println("Marca esta vacio");
            return;
        }
        String modelo = txtModelo.getText().trim();
         if(modelo.isEmpty()){
            System.out.println("Modelo esta vacio");
            return;
        }
         System.out.println(modelo);
    }//GEN-LAST:event_btnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEjemploCombo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEjemploCombo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnObtenerSeleccionado;
    private javax.swing.JComboBox<Auto> cboAutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblObtener;
    private javax.swing.JLabel lblSeleccionado;
    private javax.swing.JSpinner spnIndice;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JFormattedTextField txtModelo;
    // End of variables declaration//GEN-END:variables

    private void cargarAutos() {
        Auto autos[]={
            new Auto("Bocho","1994"),
            new Auto("Jetta","1997"),
            new Auto("Challenger","2011"),
            new Auto("Ferrari","2003")
        };
        for (Auto auto : autos) {
            cboAutos.addItem(auto);
            
        }
        spnIndice.setModel(new SpinnerNumberModel(0, 0, autos.length-1, 1));
    }
        
}
class Auto{
    
    private String Marca;
    private String Modelo;

    public Auto(String Marca, String Modelo) {
        this.Marca = Marca;
        this.Modelo = Modelo;
    }

    /**
     * Get the value of Marca
     *
     * @return the value of Marca
     */
    public String getMarca() {
        return Marca;
    }

    /**
     * Set the value of Marca
     *
     * @param Marca new value of Marca
     */
    public void setMarca(String Marca) {
        this.Marca = Marca;
    }

    /**
     * Get the value of Modelo
     *
     * @return the value of Modelo
     */
    public String getModelo() {
        return Modelo;
    }

    /**
     * Set the value of Modelo
     *
     * @param Modelo new value of Modelo
     */
    public void setModelo(String Modelo) {
        this.Modelo = Modelo;
    }
    @Override
    public String toString(){
        return Marca +" "+Modelo;
    }
            

}
